# Configure SQL Saving, MySQL is absolutely not recommended if you're using this on multiple servers
# but mysql does do data faster so up to you.
mysql:
  enabled: false
  host: localhost
  port: 3306
  dbname: DBName
  username: Username
  password: Password
  ssl: true

generator-item:
  name: '#99ff99&lChest Generator'
  lore:
    - '&7Generate items effortlessly in this'
    - '&7chest over time using a variety of'
    - '&7a different generators to choose from!'
    - ' '
    - ' &f&m-----------------------'
    - ' &f| #99ff99&lEnabled &7: &f%enabled%'
    - ' &f| #99ff99&lGenerator &7: &f%generator%'
    - ' &f| #99ff99&lOwner &7: &f%owner%'
    - ' &f&m-----------------------'
  glow: true

# The time in ticks before each item is generated in the chests.
generation-delay: 60

generators:
  0:
    name: '#2c3e50Stone Generator'
    desc:
      - '&7Use this to unlock a variety'
      - '&7of different stone-based materials.'
    cost: 0
    materials:
      GRANITE:
        amount: 1
        chance: 45
      ANDESITE:
        amount: 1
        chance: 45
      DEEPSLATE:
        amount: 1
        chance: 45
      DIORITE:
        amount: 1
        chance: 45
      TUFF:
        amount: 1
        chance: 45
      STONE:
        amount: 1
        chance: 90
      COBBLESTONE:
        amount: 1
        chance: 100
