# Configure SQL Saving, MySQL is absolutely not recommended if you're using this on multiple servers
# but mysql does do data faster so up to you.
mysql:
  enabled: false
  host: localhost
  port: 3306
  dbname: DBName
  username: Username
  password: Password
  ssl: true

generator-item:
  name: '#99ff99&lChest Generator'
  lore:
    - '&7Generate items effortlessly in this'
    - '&7chest over time using a variety of'
    - '&7a different generators to choose from!'
    - ' '
    - ' &f&m-----------------------'
    - ' &f| #99ff99&lEnabled &7: &f%enabled%'
    - ' &f| #99ff99&lGenerator &7: &f%generator%'
    - ' &f| #99ff99&lOwner &7: &f%owner%'
    - ' &f&m-----------------------'
  glow: true

# The time in ticks before each item is generated in the chests.
generation-delay: 60

# This is the way the changes for all the items are listed
# Underneath the description.
chance-mapping: '#99ff99%item% x%amount% &7: &f%chance%&f%'

generators:
  0:
    name: '#2c3e50Stone Generator'
    icon: STONE
    desc:
      - '&7Use this to unlock a variety'
      - '&7of different stone-based materials.'
      - ' '
      - '#99ff99Cost &7| &fFree'
      - '&f&m-------------'
    cost: 0
    global-chance: 20
    materials:
      GRANITE:
        amount: 1
      ANDESITE:
        amount: 1
        chance: 20
      COBBLED_DEEPSLATE:
        amount: 1
      DIORITE:
        amount: 1
      TUFF:
        amount: 1
      STONE:
        amount: 1
      COBBLESTONE:
        amount: 1
  1:
    name: '#00F260Wood Generator'
    icon: OAK_LOG
    desc:
      - '&7Use this to unlock a variety'
      - '&7of different wood-based materials.'
      - ' '
      - '#99ff99Cost &7| &f$10,000'
      - '&f&m-------------'
    cost: 10000
    materials:
      BIRCH_LOG:
        amount: 1
        chance: 16
      JUNGLE_LOG:
        amount: 1
        chance: 16
      ACACIA_LOG:
        amount: 1
        chance: 16
      DARK_OAK_LOG:
        amount: 1
        chance: 16
      SPRUCE_LOG:
        amount: 1
        chance: 16
      OAK_LOG:
        amount: 1
        chance: 100